version: '3.1'

services:
  database:
    image: bitnami/postgresql
    restart: always
    environment:
      POSTGRESQL_DATABASE: storemanager
      POSTGRESQL_PASSWORD: manager
    ports:
      - 5432:5432
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
